; GENERATED by scripts/sync-queries.js -- do not edit.
; Sources: apg2/queries/highlights.scm

; ============================================================================
; tree-sitter-apg2 -- highlight queries
;
; The Anubis code (before and after the grammar) is injected as Anubis, and
; the whole file as MAML (injections.scm). Later patterns win in Neovim.
; ============================================================================

; --- Structure --------------------------------------------------------------

[(apg2_marker) (end_marker)] @keyword.directive
(grammar_name) @module
(prelude) @comment
(comment) @comment

; --- Items ------------------------------------------------------------------

["token" "ignore"] @keyword
(declaration keyword: _ @keyword)

; Terminals (tokens) and non terminals
(symbol) @constant
(nonterminal) @type
(rule . (nonterminal) @type.definition)

; Lexer names: `lexer name.`, `apply macro lexer.`, `-name` in rules
(declaration keyword: "lexer" (symbol) @label)
(switch) @label

; Macros
(macro_name) @function.macro

; Precedence of a rule: [name]
(precedence (symbol) @attribute)

; Regular expressions: the first (...) of `token name (...)` and `ignore (...)`
(token_declaration . (symbol) . (paren) @string.regexp)
(ignore_declaration . (paren) @string.regexp)
(escape) @string.escape
(variable) @variable.builtin

; --- Punctuation ------------------------------------------------------------

["(" ")" "[" "]"] @punctuation.bracket
[":" "," "=" "." "@"] @punctuation.delimiter
