/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 0
#define TOKEN_COUNT 38
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_symbol = 1,
  sym__line = 2,
  sym_apg2_marker = 3,
  sym_grammar_name = 4,
  anon_sym_POUND = 5,
  anon_sym_LF = 6,
  sym_comment = 7,
  anon_sym_token = 8,
  anon_sym_DOT = 9,
  anon_sym_ignore = 10,
  anon_sym_lexer = 11,
  anon_sym_type = 12,
  anon_sym_left = 13,
  anon_sym_right = 14,
  anon_sym_nonassoc = 15,
  anon_sym_macro = 16,
  anon_sym_list = 17,
  anon_sym_apply = 18,
  anon_sym_function = 19,
  anon_sym_COLON = 20,
  anon_sym_COMMA = 21,
  anon_sym_EQ = 22,
  anon_sym_AT = 23,
  sym_nonterminal = 24,
  sym_macro_name = 25,
  sym_switch = 26,
  anon_sym_LBRACK = 27,
  anon_sym_RBRACK = 28,
  anon_sym_LPAREN = 29,
  aux_sym_paren_token1 = 30,
  anon_sym_RPAREN = 31,
  sym_escape = 32,
  sym__space = 33,
  sym__newline = 34,
  aux_sym__other_token1 = 35,
  aux_sym__other_token2 = 36,
  anon_sym_DASH = 37,
  sym_source_file = 38,
  sym_prelude = 39,
  sym_anubis_block = 40,
  sym_end_marker = 41,
  sym__main_item = 42,
  sym_token_declaration = 43,
  sym_ignore_declaration = 44,
  sym_declaration = 45,
  sym_macro_definition = 46,
  sym_rule = 47,
  sym_expansion = 48,
  sym__body = 49,
  sym_precedence = 50,
  sym_paren = 51,
  sym__other = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_prelude_repeat1 = 54,
  aux_sym_token_declaration_repeat1 = 55,
  aux_sym_precedence_repeat1 = 56,
  aux_sym_paren_repeat1 = 57,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_symbol] = "symbol",
  [sym__line] = "_line",
  [sym_apg2_marker] = "apg2_marker",
  [sym_grammar_name] = "grammar_name",
  [anon_sym_POUND] = "#",
  [anon_sym_LF] = "\n",
  [sym_comment] = "comment",
  [anon_sym_token] = "token",
  [anon_sym_DOT] = ".",
  [anon_sym_ignore] = "ignore",
  [anon_sym_lexer] = "lexer",
  [anon_sym_type] = "type",
  [anon_sym_left] = "left",
  [anon_sym_right] = "right",
  [anon_sym_nonassoc] = "nonassoc",
  [anon_sym_macro] = "macro",
  [anon_sym_list] = "list",
  [anon_sym_apply] = "apply",
  [anon_sym_function] = "function",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_AT] = "@",
  [sym_nonterminal] = "nonterminal",
  [sym_macro_name] = "macro_name",
  [sym_switch] = "switch",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [aux_sym_paren_token1] = "text",
  [anon_sym_RPAREN] = ")",
  [sym_escape] = "escape",
  [sym__space] = "_space",
  [sym__newline] = "_newline",
  [aux_sym__other_token1] = "_other_token1",
  [aux_sym__other_token2] = "_other_token2",
  [anon_sym_DASH] = "-",
  [sym_source_file] = "source_file",
  [sym_prelude] = "prelude",
  [sym_anubis_block] = "anubis_block",
  [sym_end_marker] = "end_marker",
  [sym__main_item] = "_main_item",
  [sym_token_declaration] = "token_declaration",
  [sym_ignore_declaration] = "ignore_declaration",
  [sym_declaration] = "declaration",
  [sym_macro_definition] = "macro_definition",
  [sym_rule] = "rule",
  [sym_expansion] = "expansion",
  [sym__body] = "_body",
  [sym_precedence] = "precedence",
  [sym_paren] = "paren",
  [sym__other] = "_other",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_prelude_repeat1] = "prelude_repeat1",
  [aux_sym_token_declaration_repeat1] = "token_declaration_repeat1",
  [aux_sym_precedence_repeat1] = "precedence_repeat1",
  [aux_sym_paren_repeat1] = "paren_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_symbol] = sym_symbol,
  [sym__line] = sym__line,
  [sym_apg2_marker] = sym_apg2_marker,
  [sym_grammar_name] = sym_grammar_name,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_LF] = anon_sym_LF,
  [sym_comment] = sym_comment,
  [anon_sym_token] = anon_sym_token,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_ignore] = anon_sym_ignore,
  [anon_sym_lexer] = anon_sym_lexer,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_left] = anon_sym_left,
  [anon_sym_right] = anon_sym_right,
  [anon_sym_nonassoc] = anon_sym_nonassoc,
  [anon_sym_macro] = anon_sym_macro,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_apply] = anon_sym_apply,
  [anon_sym_function] = anon_sym_function,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_AT] = anon_sym_AT,
  [sym_nonterminal] = sym_nonterminal,
  [sym_macro_name] = sym_macro_name,
  [sym_switch] = sym_switch,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_paren_token1] = aux_sym_paren_token1,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_escape] = sym_escape,
  [sym__space] = sym__space,
  [sym__newline] = sym__newline,
  [aux_sym__other_token1] = aux_sym__other_token1,
  [aux_sym__other_token2] = aux_sym__other_token2,
  [anon_sym_DASH] = anon_sym_DASH,
  [sym_source_file] = sym_source_file,
  [sym_prelude] = sym_prelude,
  [sym_anubis_block] = sym_anubis_block,
  [sym_end_marker] = sym_end_marker,
  [sym__main_item] = sym__main_item,
  [sym_token_declaration] = sym_token_declaration,
  [sym_ignore_declaration] = sym_ignore_declaration,
  [sym_declaration] = sym_declaration,
  [sym_macro_definition] = sym_macro_definition,
  [sym_rule] = sym_rule,
  [sym_expansion] = sym_expansion,
  [sym__body] = sym__body,
  [sym_precedence] = sym_precedence,
  [sym_paren] = sym_paren,
  [sym__other] = sym__other,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_prelude_repeat1] = aux_sym_prelude_repeat1,
  [aux_sym_token_declaration_repeat1] = aux_sym_token_declaration_repeat1,
  [aux_sym_precedence_repeat1] = aux_sym_precedence_repeat1,
  [aux_sym_paren_repeat1] = aux_sym_paren_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_apg2_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_grammar_name] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_token] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ignore] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_lexer] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_left] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_right] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nonassoc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_macro] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_apply] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_nonterminal] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [sym_switch] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_paren_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_escape] = {
    .visible = true,
    .named = true,
  },
  [sym__space] = {
    .visible = false,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__other_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__other_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_prelude] = {
    .visible = true,
    .named = true,
  },
  [sym_anubis_block] = {
    .visible = true,
    .named = true,
  },
  [sym_end_marker] = {
    .visible = true,
    .named = true,
  },
  [sym__main_item] = {
    .visible = false,
    .named = true,
  },
  [sym_token_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_ignore_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_expansion] = {
    .visible = true,
    .named = true,
  },
  [sym__body] = {
    .visible = false,
    .named = true,
  },
  [sym_precedence] = {
    .visible = true,
    .named = true,
  },
  [sym_paren] = {
    .visible = true,
    .named = true,
  },
  [sym__other] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_prelude_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_token_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_precedence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paren_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_keyword = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_keyword] = "keyword",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_keyword, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [0] = sym_macro_name,
  },
  [3] = {
    [0] = aux_sym_paren_token1,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 40,
  [43] = 39,
  [44] = 44,
  [45] = 36,
  [46] = 34,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 51,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 51,
  [62] = 49,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static const TSCharacterRange aux_sym__other_token1_character_set_1[] = {
  {0, 0x08}, {0x0e, 0x1f}, {'!', '"'}, {'$', '\''}, {'*', '+'}, {'/', '/'}, {';', '<'}, {'>', '?'},
  {'\\', '\\'}, {'^', '^'}, {'`', '`'}, {'{', 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '\n', 22,
        '#', 21,
        '(', 35,
        ')', 37,
        ',', 26,
        '-', 43,
        '.', 24,
        ':', 25,
        '=', 27,
        '@', 28,
        '[', 33,
        ']', 34,
        '\t', 39,
        '\r', 39,
        ' ', 39,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '#') ADVANCE(21);
      if (lookahead == '(') ADVANCE(35);
      if (lookahead == ')') ADVANCE(37);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 3,
        '#', 20,
        '(', 35,
        ',', 26,
        '-', 43,
        '.', 24,
        ':', 25,
        '=', 27,
        '@', 28,
        '[', 33,
        '\t', 39,
        '\r', 39,
        ' ', 39,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ']') ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 4:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 5:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(22);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '@') ADVANCE(4);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(30);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 6:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '#') ADVANCE(12);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym__line);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '2') ADVANCE(18);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == 'A') ADVANCE(14);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == 'G') ADVANCE(11);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == 'P') ADVANCE(13);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(10);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__line);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_apg2_marker);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_apg2_marker);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_grammar_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(38);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_symbol);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_nonterminal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_macro_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_switch);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_paren_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '#' &&
          lookahead != '(' &&
          lookahead != ')') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_escape);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__space);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__other_token1);
      if ((!eof && set_contains(aux_sym__other_token1_character_set_1, 12, lookahead))) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__other_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'f', 2,
        'i', 3,
        'l', 4,
        'm', 5,
        'n', 6,
        'r', 7,
        't', 8,
      );
      END_STATE();
    case 1:
      if (lookahead == 'p') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'g') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'e') ADVANCE(12);
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(17);
      if (lookahead == 'y') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'x') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 'k') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'h') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'y') ADVANCE(41);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_left);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(45);
      END_STATE();
    case 37:
      if (lookahead == 's') ADVANCE(46);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_apply);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(49);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_lexer);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_macro);
      END_STATE();
    case 46:
      if (lookahead == 's') ADVANCE(51);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_right);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_token);
      END_STATE();
    case 49:
      if (lookahead == 'o') ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_ignore);
      END_STATE();
    case 51:
      if (lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 53:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_function);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_nonassoc);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 5},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 5},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 7},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 6},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 6},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 8},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 6},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_token] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_ignore] = ACTIONS(1),
    [anon_sym_lexer] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_left] = ACTIONS(1),
    [anon_sym_right] = ACTIONS(1),
    [anon_sym_nonassoc] = ACTIONS(1),
    [anon_sym_macro] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_apply] = ACTIONS(1),
    [anon_sym_function] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_nonterminal] = ACTIONS(1),
    [sym_switch] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_escape] = ACTIONS(1),
    [sym__space] = ACTIONS(1),
    [aux_sym__other_token1] = ACTIONS(1),
    [aux_sym__other_token2] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(72),
    [sym_prelude] = STATE(68),
    [aux_sym_prelude_repeat1] = STATE(57),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__line] = ACTIONS(5),
    [sym_apg2_marker] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      anon_sym_token,
    ACTIONS(19), 1,
      anon_sym_ignore,
    ACTIONS(23), 1,
      sym_nonterminal,
    ACTIONS(25), 1,
      sym_macro_name,
    STATE(53), 1,
      sym_end_marker,
    ACTIONS(15), 2,
      anon_sym_LF,
      sym_comment,
    STATE(5), 8,
      sym__main_item,
      sym_token_declaration,
      sym_ignore_declaration,
      sym_declaration,
      sym_macro_definition,
      sym_rule,
      sym_expansion,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 9,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
  [50] = 11,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      anon_sym_token,
    ACTIONS(19), 1,
      anon_sym_ignore,
    ACTIONS(23), 1,
      sym_nonterminal,
    ACTIONS(25), 1,
      sym_macro_name,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      sym_end_marker,
    ACTIONS(29), 2,
      anon_sym_LF,
      sym_comment,
    STATE(7), 8,
      sym__main_item,
      sym_token_declaration,
      sym_ignore_declaration,
      sym_declaration,
      sym_macro_definition,
      sym_rule,
      sym_expansion,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 9,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
  [100] = 11,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      anon_sym_token,
    ACTIONS(19), 1,
      anon_sym_ignore,
    ACTIONS(23), 1,
      sym_nonterminal,
    ACTIONS(25), 1,
      sym_macro_name,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    STATE(56), 1,
      sym_end_marker,
    ACTIONS(33), 2,
      anon_sym_LF,
      sym_comment,
    STATE(8), 8,
      sym__main_item,
      sym_token_declaration,
      sym_ignore_declaration,
      sym_declaration,
      sym_macro_definition,
      sym_rule,
      sym_expansion,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 9,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
  [150] = 11,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      anon_sym_token,
    ACTIONS(19), 1,
      anon_sym_ignore,
    ACTIONS(23), 1,
      sym_nonterminal,
    ACTIONS(25), 1,
      sym_macro_name,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_end_marker,
    ACTIONS(33), 2,
      anon_sym_LF,
      sym_comment,
    STATE(8), 8,
      sym__main_item,
      sym_token_declaration,
      sym_ignore_declaration,
      sym_declaration,
      sym_macro_definition,
      sym_rule,
      sym_expansion,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 9,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
  [200] = 11,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      anon_sym_token,
    ACTIONS(19), 1,
      anon_sym_ignore,
    ACTIONS(23), 1,
      sym_nonterminal,
    ACTIONS(25), 1,
      sym_macro_name,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_end_marker,
    ACTIONS(37), 2,
      anon_sym_LF,
      sym_comment,
    STATE(4), 8,
      sym__main_item,
      sym_token_declaration,
      sym_ignore_declaration,
      sym_declaration,
      sym_macro_definition,
      sym_rule,
      sym_expansion,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 9,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
  [250] = 11,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_symbol,
    ACTIONS(13), 1,
      anon_sym_POUND,
    ACTIONS(17), 1,
      anon_sym_token,
    ACTIONS(19), 1,
      anon_sym_ignore,
    ACTIONS(23), 1,
      sym_nonterminal,
    ACTIONS(25), 1,
      sym_macro_name,
    STATE(53), 1,
      sym_end_marker,
    ACTIONS(33), 2,
      anon_sym_LF,
      sym_comment,
    STATE(8), 8,
      sym__main_item,
      sym_token_declaration,
      sym_ignore_declaration,
      sym_declaration,
      sym_macro_definition,
      sym_rule,
      sym_expansion,
      aux_sym_source_file_repeat1,
    ACTIONS(21), 9,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
  [300] = 9,
    ACTIONS(41), 1,
      sym_symbol,
    ACTIONS(47), 1,
      anon_sym_token,
    ACTIONS(50), 1,
      anon_sym_ignore,
    ACTIONS(56), 1,
      sym_nonterminal,
    ACTIONS(59), 1,
      sym_macro_name,
    ACTIONS(39), 2,
      ts_builtin_sym_end,
      anon_sym_POUND,
    ACTIONS(44), 2,
      anon_sym_LF,
      sym_comment,
    STATE(8), 8,
      sym__main_item,
      sym_token_declaration,
      sym_ignore_declaration,
      sym_declaration,
      sym_macro_definition,
      sym_rule,
      sym_expansion,
      aux_sym_source_file_repeat1,
    ACTIONS(53), 9,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
  [345] = 6,
    ACTIONS(64), 1,
      anon_sym_DOT,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_DASH,
    STATE(21), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(62), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [379] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_DOT,
    ACTIONS(76), 1,
      anon_sym_DASH,
    STATE(12), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(72), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [413] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(78), 1,
      anon_sym_DOT,
    STATE(21), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(62), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [447] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(80), 1,
      anon_sym_DOT,
    STATE(21), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(62), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [481] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(82), 1,
      anon_sym_DOT,
    STATE(21), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(62), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [515] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(84), 1,
      anon_sym_DOT,
    STATE(21), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(62), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [549] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(88), 1,
      anon_sym_DOT,
    ACTIONS(90), 1,
      anon_sym_DASH,
    STATE(13), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(86), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [583] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_DASH,
    ACTIONS(92), 1,
      anon_sym_DOT,
    STATE(21), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(62), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [617] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(96), 1,
      anon_sym_DOT,
    ACTIONS(98), 1,
      anon_sym_DASH,
    STATE(14), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(94), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [651] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(102), 1,
      anon_sym_DOT,
    ACTIONS(104), 1,
      anon_sym_DASH,
    STATE(9), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(100), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [685] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      anon_sym_DOT,
    ACTIONS(110), 1,
      anon_sym_DASH,
    STATE(16), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(106), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [719] = 6,
    ACTIONS(66), 1,
      anon_sym_LBRACK,
    ACTIONS(68), 1,
      anon_sym_LPAREN,
    ACTIONS(114), 1,
      anon_sym_DOT,
    ACTIONS(116), 1,
      anon_sym_DASH,
    STATE(11), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(112), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [753] = 6,
    ACTIONS(121), 1,
      anon_sym_DOT,
    ACTIONS(123), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LPAREN,
    ACTIONS(129), 1,
      anon_sym_DASH,
    STATE(21), 5,
      sym__body,
      sym_precedence,
      sym_paren,
      sym__other,
      aux_sym_token_declaration_repeat1,
    ACTIONS(118), 12,
      anon_sym_POUND,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [787] = 2,
    ACTIONS(132), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(134), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [810] = 2,
    ACTIONS(136), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(138), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [833] = 2,
    ACTIONS(140), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(142), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [856] = 2,
    ACTIONS(144), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(146), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [879] = 2,
    ACTIONS(148), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(150), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [902] = 2,
    ACTIONS(152), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(154), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [925] = 2,
    ACTIONS(156), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(158), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [948] = 2,
    ACTIONS(160), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(162), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [971] = 2,
    ACTIONS(164), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(166), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [994] = 2,
    ACTIONS(168), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(170), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [1017] = 2,
    ACTIONS(172), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(174), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [1040] = 2,
    ACTIONS(176), 6,
      ts_builtin_sym_end,
      anon_sym_POUND,
      anon_sym_LF,
      sym_comment,
      sym_nonterminal,
      sym_macro_name,
    ACTIONS(178), 12,
      anon_sym_token,
      anon_sym_ignore,
      anon_sym_lexer,
      anon_sym_type,
      anon_sym_left,
      anon_sym_right,
      anon_sym_nonassoc,
      anon_sym_macro,
      anon_sym_list,
      anon_sym_apply,
      anon_sym_function,
      sym_symbol,
  [1063] = 2,
    ACTIONS(182), 1,
      anon_sym_DASH,
    ACTIONS(180), 15,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [1084] = 2,
    ACTIONS(186), 1,
      anon_sym_DASH,
    ACTIONS(184), 15,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [1105] = 2,
    ACTIONS(190), 1,
      anon_sym_DASH,
    ACTIONS(188), 15,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [1126] = 2,
    ACTIONS(194), 1,
      anon_sym_DASH,
    ACTIONS(192), 15,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [1147] = 2,
    ACTIONS(198), 1,
      anon_sym_DASH,
    ACTIONS(196), 15,
      anon_sym_POUND,
      anon_sym_DOT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_AT,
      sym_symbol,
      sym_nonterminal,
      sym_switch,
      anon_sym_LBRACK,
      anon_sym_LPAREN,
      sym__space,
      sym__newline,
      aux_sym__other_token1,
      aux_sym__other_token2,
  [1168] = 6,
    ACTIONS(200), 1,
      anon_sym_POUND,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      aux_sym_paren_token1,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    ACTIONS(208), 2,
      sym_escape,
      sym__newline,
    STATE(41), 2,
      sym_paren,
      aux_sym_paren_repeat1,
  [1189] = 6,
    ACTIONS(200), 1,
      anon_sym_POUND,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      aux_sym_paren_token1,
    ACTIONS(210), 1,
      anon_sym_RPAREN,
    ACTIONS(212), 2,
      sym_escape,
      sym__newline,
    STATE(39), 2,
      sym_paren,
      aux_sym_paren_repeat1,
  [1210] = 6,
    ACTIONS(214), 1,
      anon_sym_POUND,
    ACTIONS(217), 1,
      anon_sym_LPAREN,
    ACTIONS(220), 1,
      aux_sym_paren_token1,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
    ACTIONS(225), 2,
      sym_escape,
      sym__newline,
    STATE(41), 2,
      sym_paren,
      aux_sym_paren_repeat1,
  [1231] = 6,
    ACTIONS(200), 1,
      anon_sym_POUND,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      aux_sym_paren_token1,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    ACTIONS(230), 2,
      sym_escape,
      sym__newline,
    STATE(43), 2,
      sym_paren,
      aux_sym_paren_repeat1,
  [1252] = 6,
    ACTIONS(200), 1,
      anon_sym_POUND,
    ACTIONS(202), 1,
      anon_sym_LPAREN,
    ACTIONS(204), 1,
      aux_sym_paren_token1,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
    ACTIONS(208), 2,
      sym_escape,
      sym__newline,
    STATE(41), 2,
      sym_paren,
      aux_sym_paren_repeat1,
  [1273] = 2,
    ACTIONS(234), 1,
      anon_sym_POUND,
    ACTIONS(236), 5,
      anon_sym_LPAREN,
      aux_sym_paren_token1,
      anon_sym_RPAREN,
      sym_escape,
      sym__newline,
  [1284] = 2,
    ACTIONS(190), 1,
      anon_sym_POUND,
    ACTIONS(188), 5,
      anon_sym_LPAREN,
      aux_sym_paren_token1,
      anon_sym_RPAREN,
      sym_escape,
      sym__newline,
  [1295] = 2,
    ACTIONS(182), 1,
      anon_sym_POUND,
    ACTIONS(180), 5,
      anon_sym_LPAREN,
      aux_sym_paren_token1,
      anon_sym_RPAREN,
      sym_escape,
      sym__newline,
  [1306] = 5,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(238), 1,
      sym__line,
    ACTIONS(240), 1,
      sym_grammar_name,
    STATE(49), 1,
      aux_sym_prelude_repeat1,
    STATE(67), 1,
      sym_anubis_block,
  [1322] = 5,
    ACTIONS(238), 1,
      sym__line,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 1,
      sym_grammar_name,
    STATE(49), 1,
      aux_sym_prelude_repeat1,
    STATE(69), 1,
      sym_anubis_block,
  [1338] = 3,
    ACTIONS(248), 1,
      sym__line,
    STATE(55), 1,
      aux_sym_prelude_repeat1,
    ACTIONS(246), 2,
      ts_builtin_sym_end,
      sym_grammar_name,
  [1349] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 1,
      sym__line,
    STATE(62), 1,
      aux_sym_prelude_repeat1,
    STATE(70), 1,
      sym_anubis_block,
  [1362] = 3,
    ACTIONS(254), 1,
      sym__line,
    STATE(51), 1,
      aux_sym_prelude_repeat1,
    ACTIONS(252), 2,
      ts_builtin_sym_end,
      sym_apg2_marker,
  [1373] = 4,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 1,
      sym__line,
    STATE(62), 1,
      aux_sym_prelude_repeat1,
    STATE(73), 1,
      sym_anubis_block,
  [1386] = 4,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(250), 1,
      sym__line,
    STATE(62), 1,
      aux_sym_prelude_repeat1,
    STATE(71), 1,
      sym_anubis_block,
  [1399] = 3,
    ACTIONS(259), 1,
      sym__space,
    STATE(54), 1,
      aux_sym_precedence_repeat1,
    ACTIONS(257), 2,
      sym_symbol,
      anon_sym_RBRACK,
  [1410] = 3,
    ACTIONS(262), 1,
      sym__line,
    STATE(55), 1,
      aux_sym_prelude_repeat1,
    ACTIONS(252), 2,
      ts_builtin_sym_end,
      sym_grammar_name,
  [1421] = 4,
    ACTIONS(250), 1,
      sym__line,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
    STATE(62), 1,
      aux_sym_prelude_repeat1,
    STATE(74), 1,
      sym_anubis_block,
  [1434] = 3,
    ACTIONS(269), 1,
      sym__line,
    STATE(51), 1,
      aux_sym_prelude_repeat1,
    ACTIONS(267), 2,
      ts_builtin_sym_end,
      sym_apg2_marker,
  [1445] = 3,
    ACTIONS(271), 1,
      sym_symbol,
    ACTIONS(273), 1,
      sym__space,
    STATE(64), 1,
      aux_sym_precedence_repeat1,
  [1455] = 3,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
    ACTIONS(277), 1,
      sym__space,
    STATE(54), 1,
      aux_sym_precedence_repeat1,
  [1465] = 3,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
    ACTIONS(279), 1,
      sym__space,
    STATE(65), 1,
      aux_sym_precedence_repeat1,
  [1475] = 3,
    ACTIONS(252), 1,
      ts_builtin_sym_end,
    ACTIONS(281), 1,
      sym__line,
    STATE(61), 1,
      aux_sym_prelude_repeat1,
  [1485] = 3,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
    ACTIONS(284), 1,
      sym__line,
    STATE(61), 1,
      aux_sym_prelude_repeat1,
  [1495] = 3,
    ACTIONS(286), 1,
      anon_sym_RBRACK,
    ACTIONS(288), 1,
      sym__space,
    STATE(59), 1,
      aux_sym_precedence_repeat1,
  [1505] = 3,
    ACTIONS(277), 1,
      sym__space,
    ACTIONS(290), 1,
      sym_symbol,
    STATE(54), 1,
      aux_sym_precedence_repeat1,
  [1515] = 3,
    ACTIONS(277), 1,
      sym__space,
    ACTIONS(292), 1,
      anon_sym_RBRACK,
    STATE(54), 1,
      aux_sym_precedence_repeat1,
  [1525] = 1,
    ACTIONS(294), 2,
      ts_builtin_sym_end,
      sym__line,
  [1530] = 2,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(296), 1,
      sym_grammar_name,
  [1537] = 2,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(298), 1,
      sym_apg2_marker,
  [1544] = 2,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(240), 1,
      sym_grammar_name,
  [1551] = 1,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
  [1555] = 1,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
  [1559] = 1,
    ACTIONS(300), 1,
      ts_builtin_sym_end,
  [1563] = 1,
    ACTIONS(265), 1,
      ts_builtin_sym_end,
  [1567] = 1,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 200,
  [SMALL_STATE(7)] = 250,
  [SMALL_STATE(8)] = 300,
  [SMALL_STATE(9)] = 345,
  [SMALL_STATE(10)] = 379,
  [SMALL_STATE(11)] = 413,
  [SMALL_STATE(12)] = 447,
  [SMALL_STATE(13)] = 481,
  [SMALL_STATE(14)] = 515,
  [SMALL_STATE(15)] = 549,
  [SMALL_STATE(16)] = 583,
  [SMALL_STATE(17)] = 617,
  [SMALL_STATE(18)] = 651,
  [SMALL_STATE(19)] = 685,
  [SMALL_STATE(20)] = 719,
  [SMALL_STATE(21)] = 753,
  [SMALL_STATE(22)] = 787,
  [SMALL_STATE(23)] = 810,
  [SMALL_STATE(24)] = 833,
  [SMALL_STATE(25)] = 856,
  [SMALL_STATE(26)] = 879,
  [SMALL_STATE(27)] = 902,
  [SMALL_STATE(28)] = 925,
  [SMALL_STATE(29)] = 948,
  [SMALL_STATE(30)] = 971,
  [SMALL_STATE(31)] = 994,
  [SMALL_STATE(32)] = 1017,
  [SMALL_STATE(33)] = 1040,
  [SMALL_STATE(34)] = 1063,
  [SMALL_STATE(35)] = 1084,
  [SMALL_STATE(36)] = 1105,
  [SMALL_STATE(37)] = 1126,
  [SMALL_STATE(38)] = 1147,
  [SMALL_STATE(39)] = 1168,
  [SMALL_STATE(40)] = 1189,
  [SMALL_STATE(41)] = 1210,
  [SMALL_STATE(42)] = 1231,
  [SMALL_STATE(43)] = 1252,
  [SMALL_STATE(44)] = 1273,
  [SMALL_STATE(45)] = 1284,
  [SMALL_STATE(46)] = 1295,
  [SMALL_STATE(47)] = 1306,
  [SMALL_STATE(48)] = 1322,
  [SMALL_STATE(49)] = 1338,
  [SMALL_STATE(50)] = 1349,
  [SMALL_STATE(51)] = 1362,
  [SMALL_STATE(52)] = 1373,
  [SMALL_STATE(53)] = 1386,
  [SMALL_STATE(54)] = 1399,
  [SMALL_STATE(55)] = 1410,
  [SMALL_STATE(56)] = 1421,
  [SMALL_STATE(57)] = 1434,
  [SMALL_STATE(58)] = 1445,
  [SMALL_STATE(59)] = 1455,
  [SMALL_STATE(60)] = 1465,
  [SMALL_STATE(61)] = 1475,
  [SMALL_STATE(62)] = 1485,
  [SMALL_STATE(63)] = 1495,
  [SMALL_STATE(64)] = 1505,
  [SMALL_STATE(65)] = 1515,
  [SMALL_STATE(66)] = 1525,
  [SMALL_STATE(67)] = 1530,
  [SMALL_STATE(68)] = 1537,
  [SMALL_STATE(69)] = 1544,
  [SMALL_STATE(70)] = 1551,
  [SMALL_STATE(71)] = 1555,
  [SMALL_STATE(72)] = 1559,
  [SMALL_STATE(73)] = 1563,
  [SMALL_STATE(74)] = 1567,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_token_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_token_declaration_repeat1, 2, 0, 0),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_token_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_token_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [129] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_token_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token_declaration, 2, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token_declaration, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_definition, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignore_declaration, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignore_declaration, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_token_declaration, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_token_declaration, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ignore_declaration, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ignore_declaration, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 2, 0, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 2, 0, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 1),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expansion, 3, 0, 2),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expansion, 3, 0, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_rule, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_definition, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2, 0, 1),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2, 0, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 2, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 2, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_precedence, 3, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_precedence, 3, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_precedence, 5, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_precedence, 5, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_precedence, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_precedence, 4, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [214] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paren_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [220] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paren_repeat1, 2, 0, 0),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paren_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paren_repeat1, 1, 0, 3),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paren_repeat1, 1, 0, 3),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_anubis_block, 1, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prelude_repeat1, 2, 0, 0),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prelude_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_precedence_repeat1, 2, 0, 0),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_precedence_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [262] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_prelude_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 6, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prelude, 1, 0, 0),
  [269] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prelude_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_marker, 1, 0, 0),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [300] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 7, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_apg2(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_symbol,
    .primary_state_ids = ts_primary_state_ids,
    .name = "apg2",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
