; GENERATED by scripts/sync-queries.js -- do not edit.
; Sources: queries/highlights.scm + editors/neovim/queries-overlay/highlights.scm

; ============================================================================
; tree-sitter-anubis -- highlight queries
;
; PRINCIPLE: a token is coloured by WHAT IT IS, not by where it sits.
;
;   Part 1 (base layer) only uses leaf patterns: they also match inside ERROR
;   nodes, so a paragraph you are still typing keeps its colours.
;   Part 2 (refinements) adds a few contextual captures. Each one only makes
;   an identifier MORE specific; if it fails (partial code), the base colour
;   remains.
;
; Later patterns win over earlier ones in Neovim.
; Captures follow the Neovim standard set (:h treesitter-highlight-groups);
; unusual sub-captures (e.g. @type.parameter) fall back to their parent.
; ============================================================================


; ============================================================================
; PART 1 -- BASE LAYER (context-free)
; ============================================================================

; --- Text outside paragraphs ------------------------------------------------

(out_comment) @comment.documentation   ; prose between paragraphs
(stray_text)  @comment.warning         ; column-0 text that is NOT a paragraph
(todo_line)   @comment.todo

; --- Comments inside paragraphs ---------------------------------------------

(comment)       @comment
(block_comment) @comment


; --- Paragraph keywords (always at column 0) --------------------------------

[(kw_define) (kw_module)]    @keyword.function
[(kw_type) (kw_type_alias)]  @keyword.type
[(kw_describe) (kw_c_constructors)] @keyword
(kw_read)                    @keyword.import
(kw_execute)                 @keyword.directive

; The paragraph terminator: important, so it gets its own colour.
(par_end) @punctuation.special


; --- Keywords inside paragraphs ---------------------------------------------

["if" "then" "else" "is" "not" "since"] @keyword.conditional

["with"] @keyword
(lazy)   @keyword.modifier
["cross_recursive"] @keyword.function
["delegate" "checking every" "milliseconds, wait for"] @keyword.coroutine
["should_not_happen"] @keyword.exception
["todo"] @keyword.todo

(builtin_kw) @function.builtin


; --- Punctuation: identical everywhere --------------------------------------

["(" ")" "[" "]" "{" "}"] @punctuation.bracket
","                       @punctuation.delimiter
(par_type ":" @punctuation.delimiter)                 ; Type Foo: ...  (binary `a : b` is (colon), an operator)
["@" "@@"]                @punctuation.special
(cons_dot)                @punctuation.delimiter      ; [h . t]


; --- Operators: identical everywhere -----------------------------------------
; (every operator token is its own named node, see TOKS in grammar.js)

[
  (doublecolon) (colon) (semicolon)
  (vbar) (ampersand) (leftshift) (rightshift) (tilde)
  (equals) (eqlike) (exchange) (write)
  (plus) (plusplus) (minus) (absminus) (star) (percent)
  (slash) (backslash) (dot) (carret) (dotdot) (dotsup)
] @operator

"=" @operator

; Function-type arrow, including the glued `)->`
(arrow) @operator

; Lambda introducer `)|->` and `)|-name->`
(mapsto) @keyword.function

; opening '(' of the lambda, must be higher priority than bracket (default 100)
(lambda "(" @keyword.function (#set! priority 110))


; --- Types --------------------------------------------------------------------

(ty_name)  @type
(ty_pname) @type.parameter            ; $T, $Elem
(type_joker) @type.jocker

;((ty_name) @type.builtin
; (#any-of? @type.builtin
;   "Int" "Float" "String" "ByteArray" "Omega" "Covered"
;   "Var" "QueueIn" "QueueOut" "StructPtr" "Opaque"
;   "RStream" "WStream" "RWStream"
;   "FunctionFamily" "Listener"))


; --- Literals ---------------------------------------------------------------

(lit_integer) @number
(lit_float)   @number.float
(lit_char)    @character
(lit_string)  @string


; --- Identifiers ------------------------------------------------------------

(identifier) @variable

((identifier) @variable.builtin
 (#eq? @variable.builtin "_"))


; ============================================================================
; PART 2 -- REFINEMENTS (contextual, identifiers and a few operators only)
; ============================================================================

; --- Definitions ------------------------------------------------------------

(par_def name: (identifier) @function)

(type_decl name: (ty_name) @type.definition)
(par_c_constructors name: (ty_name) @type.definition)

(par_type_alt name: (identifier) @constructor)
(par_type_alt_factor name: (identifier) @variable.member)


; --- Parameters -------------------------------------------------------------

(operand arg: (identifier) @variable.parameter)
(farg    arg: (identifier) @variable.parameter)

; Names inside function / tuple types: (Int x, Int y) -> T
(type name: (identifier) @variable.parameter)

; Named recursive lambda: (Int x) |-loop-> ...
(mapsto (identifier) @function)


; --- Calls, updates, bindings -----------------------------------------------

(apply fun: (term (identifier) @function.call))
(replace field: (identifier) @variable.member)
(with name: (identifier) @variable)


; --- Patterns (constructors) ------------------------------------------------

(case pattern: (term (identifier) @constructor))
(case pattern: (term (apply fun: (term (identifier) @constructor))))
(conditional pattern: (term (identifier) @constructor))
(conditional pattern: (term (apply fun: (term (identifier) @constructor))))


; --- Side effects on Var(T) -------------------------------------------------
; `x <- v`, `x <-> y`, `*x`: stand out from pure arithmetic.

(binary_op bop: [(write) (exchange)] @keyword.operator)
(unary_op  uop: (star) @keyword.operator)


; --- Small paragraphs -------------------------------------------------------

(par_read path: (_) @string.special.path)
(par_execute command: (command) @string.special)
(adm_dest (lit_string) @string.special.path)


; --- APG2 blocks ------------------------------------------------------------

[(apg2_marker) (apg2_name)] @keyword.directive
(apg2_token)  @variable
(apg2_ignore) @variable
(apg2_prec)   @punctuation.delimiter
(apg2_lexer)  @string
(apg2_type)   @type
(apg2_macro)  @function.macro
(apg2_other)  @none

; ---- editors/neovim/queries-overlay/highlights.scm ----

; ============================================================================
; Neovim-specific highlights, appended AFTER queries/highlights.scm by
; scripts/sync-queries.js. Later patterns win: this can refine captures.
; ============================================================================

; --- Spell checking (Neovim-only captures) ----------------------------------
; Check the prose between paragraphs and comments, never code.

[(out_comment) (comment) (block_comment) (todo_line)] @spell
(stray_text) @nospell


; --- Standard library -------------------------------------------------------
; Name-based captures for well-known constructors. Without a colour of their
; own, they fall back to @constructor. lua/anubis/init.lua links them to
; DiagnosticOk / DiagnosticError by default; a colorscheme or the user can
; override `@constructor.success.anubis` etc.

((identifier) @constructor.success (#eq? @constructor.success "success"))
((identifier) @constructor.failure (#eq? @constructor.failure "failure"))
((identifier) @boolean (#any-of? @boolean "true" "false"))
; ((ty_name) @type.builtin (#any-of? @type.builtin "Maybe" "List" "Bool" "One"))
