; GENERATED by scripts/sync-queries.js -- do not edit.
; Sources: queries/locals.scm

; ============================================================================
; tree-sitter-anubis -- locals (scopes, definitions, references)
; ============================================================================

; --- Scopes -----------------------------------------------------------------

(par_def)     @local.scope
(lambda)      @local.scope
(with)        @local.scope
(case)        @local.scope   ; pattern bindings: visible in the clause body
(conditional) @local.scope   ; since t is PATTERN, body  /  if t is not PATTERN ...
(cross_rec)   @local.scope   ; the group of mutually recursive lambdas


; --- Definitions: paragraph, parameters, with -------------------------------

(par_def name: (identifier) @local.definition.function)
(operand arg: (identifier) @local.definition.parameter)
(farg    arg: (identifier) @local.definition.parameter)
(with   name: (identifier) @local.definition.var)


; --- Definitions: pattern variables -----------------------------------------
; Patterns have their own nodes (pattern_*), so nesting depth is unlimited.
;
; A bare identifier as the WHOLE pattern (`nil then ...`) is a nullary
; constructor, so it is deliberately not a definition: only identifiers
; NESTED in a pattern are bindings. `_` binds nothing.

; Constructor arguments, list / tuple items, operator operands:
;   success(x), cons(h, t), [h . t], (a, b), a + b, ~a
((pattern_constructor (pattern (identifier) @local.definition.var))
 (#not-eq? @local.definition.var "_"))
((pattern_list (pattern (identifier) @local.definition.var))
 (#not-eq? @local.definition.var "_"))
((pattern_tuple (pattern (identifier) @local.definition.var))
 (#not-eq? @local.definition.var "_"))
((pattern_binary (pattern (identifier) @local.definition.var))
 (#not-eq? @local.definition.var "_"))
((pattern_unary (pattern (identifier) @local.definition.var))
 (#not-eq? @local.definition.var "_"))

; Typed symbol: always a binding, even as the whole pattern
;   error(Error_anubis150_parser er), since x is Int n, ...
((typed_symbol name: (identifier) @local.definition.var)
 (#not-eq? @local.definition.var "_"))


; --- Definitions: named recursive lambdas -----------------------------------

; (Int x) |-loop-> ... loop(x - 1) ...
; The name lives in the lambda's own scope: visible in its body only.
(lambda (mapsto (identifier) @local.definition.function))

; cross_recursive { (..) |-f-> ... g(..) ..., (..) |-g-> ... f(..) ... }
; Each name is lifted one scope up (to cross_rec), so sibling lambdas see it.
; `#set! ... scope "parent"` is the nvim-treesitter convention.
((cross_rec (lambda (mapsto (identifier) @local.definition.function)))
 (#set! definition.function.scope "parent"))


; --- References -------------------------------------------------------------

(term (identifier) @local.reference)
