; GENERATED by scripts/sync-queries.js -- do not edit.
; Sources: queries/locals.scm

; ============================================================================
; tree-sitter-anubis -- locals (scopes, definitions, references)
; ============================================================================

; --- Scopes -----------------------------------------------------------------

(par_def)     @local.scope
(lambda)      @local.scope
(with)        @local.scope
(case)        @local.scope   ; pattern bindings: visible in the clause body
(conditional) @local.scope   ; since t is PATTERN, body  /  if t is not PATTERN ...
(cross_rec)   @local.scope   ; the group of mutually recursive lambdas


; --- Definitions: paragraph, parameters, with -------------------------------

(par_def name: (identifier) @local.definition.function)
(operand arg: (identifier) @local.definition.parameter)
(farg    arg: (identifier) @local.definition.parameter)
(with   name: (identifier) @local.definition.var)


; --- Definitions: pattern variables -----------------------------------------
; `(_ pattern: ...)` matches both `case` and `conditional` (since / is not).
;
; A bare identifier as the WHOLE pattern (`nil then ...`) is a nullary
; constructor, so it is deliberately not a definition. Identifiers in argument
; positions are bindings. Queries cannot recurse, so nesting is covered to
; depth 2, which handles the usual shapes. `_` binds nothing.

; Constructor arguments: success(x), cons(h, t)
((_ pattern: (term (apply arg: (term (identifier) @local.definition.var))))
 (#not-eq? @local.definition.var "_"))

; One level of nesting: success(cons(h, t))
((_ pattern: (term (apply arg: (term (apply arg: (term (identifier) @local.definition.var))))))
 (#not-eq? @local.definition.var "_"))

; List patterns: [h . t], [a, b], and inside a constructor: success([h . t])
((_ pattern: (term (list (term (identifier) @local.definition.var))))
 (#not-eq? @local.definition.var "_"))
((_ pattern: (term (apply arg: (term (list (term (identifier) @local.definition.var))))))
 (#not-eq? @local.definition.var "_"))

; Tuple patterns: (a, b)
((_ pattern: (term (tuple (term (identifier) @local.definition.var))))
 (#not-eq? @local.definition.var "_"))

; Operator-shaped patterns, for types whose alternatives are operators: a + b, ~a
((_ pattern: (term (binary_op left: (term (identifier) @local.definition.var))))
 (#not-eq? @local.definition.var "_"))
((_ pattern: (term (binary_op right: (term (identifier) @local.definition.var))))
 (#not-eq? @local.definition.var "_"))
((_ pattern: (term (unary_op rule: (term (identifier) @local.definition.var))))
 (#not-eq? @local.definition.var "_"))


; --- Definitions: named recursive lambdas -----------------------------------

; (Int x) |-loop-> ... loop(x - 1) ...
; The name lives in the lambda's own scope: visible in its body only.
(lambda (mapsto (identifier) @local.definition.function))

; cross_recursive { (..) |-f-> ... g(..) ..., (..) |-g-> ... f(..) ... }
; Each name is lifted one scope up (to cross_rec), so sibling lambdas see it.
; `#set! ... scope "parent"` is the nvim-treesitter convention.
((cross_rec (lambda (mapsto (identifier) @local.definition.function)))
 (#set! definition.function.scope "parent"))


; --- References -------------------------------------------------------------

(term (identifier) @local.reference)
