#!/usr/bin/env node
// Generate editor-specific query files from the canonical ones of each grammar.
//
//   node scripts/sync-queries.js           write the generated files
//   node scripts/sync-queries.js --check   verify they are up to date (for CI)
//
// For each editor and each grammar (tree-sitter.json, see grammars.js), every
// query file is:
//
//   header  +  <grammar>/queries/<name>.scm  +  editors/<editor>/overlays/<grammar>/<name>.scm
//
// Either part may be missing (an overlay-only file, e.g. Neovim folds, is
// allowed). The overlay comes LAST: in Neovim, later patterns win, so the
// overlay can refine or override canonical captures.
//
// Adding an editor = adding an entry to EDITORS. `transform` can rewrite the
// text, e.g. to rename captures for an editor with a different naming scheme.

"use strict";
const fs = require("fs");
const path = require("path");
const { ROOT, grammars } = require("./grammars");

const EDITORS = [
  {
    name: "neovim",
    out: (lang) => `editors/neovim/queries/${lang}`,   // Neovim reads queries/<language>/
    overlay: (lang) => `editors/neovim/overlays/${lang}`,
    transform: (text) => text,
  },
  // Example for later:
  // { name: "helix",
  //   out: (lang) => `editors/helix/queries/${lang}`,
  //   overlay: (lang) => `editors/helix/overlays/${lang}`,
  //   transform: (text) => text.replace(/@keyword\.conditional\b/g, "@keyword.control.conditional") },
];

// One target per (editor, grammar).
const TARGETS = EDITORS.flatMap((e) => grammars.map((g) => ({
  name: `${e.name} (${g.name})`,
  canonical: `${g.path}/queries`,
  out: e.out(g.name),
  overlay: e.overlay(g.name),
  transform: e.transform,
})));

const HEADER = (sources) =>
  "; GENERATED by scripts/sync-queries.js -- do not edit.\n" +
  `; Sources: ${sources.join(" + ")}\n\n`;


// --- helpers -----------------------------------------------------------------

const rel = (p) => path.relative(ROOT, p).split(path.sep).join("/");

function scmFiles(dir) {
  const abs = path.join(ROOT, dir);
  if (!fs.existsSync(abs)) return [];
  return fs.readdirSync(abs).filter((f) => f.endsWith(".scm")).sort();
}

function read(file) {
  // Normalise line endings and make sure the text ends with one newline.
  return fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n").replace(/\n*$/, "\n");
}

// Returns { "<abs output path>": { content, sources: [<abs source path>...] } }
// for one target.
function generate(target) {
  const names = new Set([...scmFiles(target.canonical), ...scmFiles(target.overlay)]);
  const out = {};
  for (const name of [...names].sort()) {
    const parts = [];
    const sources = [];
    for (const dir of [target.canonical, target.overlay]) {
      const file = path.join(ROOT, dir, name);
      if (fs.existsSync(file)) {
        sources.push(rel(file));
        parts.push(
          (sources.length > 1 ? `\n; ---- ${rel(file)} ----\n\n` : "") + read(file)
        );
      }
    }
    out[path.join(ROOT, target.out, name)] = {
      content: HEADER(sources) + target.transform(parts.join("")),
      sources: sources.map((f) => path.join(ROOT, f)),
    };
  }
  return out;
}


// --- main --------------------------------------------------------------------

const check = process.argv.includes("--check");
const problems = [];

for (const target of TARGETS) {
  const wanted = generate(target);
  const outDir = path.join(ROOT, target.out);

  // Stale files: generated earlier, but their source no longer exists.
  for (const f of scmFiles(target.out)) {
    const abs = path.join(outDir, f);
    if (!(abs in wanted)) {
      if (check) problems.push(`stale:    ${rel(abs)}`);
      else { fs.unlinkSync(abs); console.log(`removed  ${rel(abs)}`); }
    }
  }

  for (const [abs, { content, sources }] of Object.entries(wanted)) {
    const current = fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
    if (current === content) {
      // Up to date, but maybe older than its sources (e.g. after a checkout):
      // refresh its time, which editors use to detect stale files.
      if (!check) {
        const newest = Math.max(...sources.map((f) => fs.statSync(f).mtimeMs));
        if (fs.statSync(abs).mtimeMs < newest) {
          const now = new Date();
          fs.utimesSync(abs, now, now);
          console.log(`touched  ${rel(abs)}`);
        }
      }
      continue;
    }
    if (check) {
      problems.push(`${current === null ? "missing:" : "outdated:"} ${rel(abs)}`);
    } else {
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, content);
      console.log(`wrote    ${rel(abs)}`);
    }
  }
}

if (check) {
  if (problems.length) {
    console.error("Generated queries are out of date:\n  " + problems.join("\n  "));
    console.error("Run: node scripts/sync-queries.js");
    process.exit(1);
  }
  console.log("Generated queries are up to date.");
}
